from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QFile

from shifry import Shifry

class Ui_MainWindow(object):
    langs = {
        'ru_short': "Русский без 'ё'",
        'ru': 'Русский',
        'en': 'English',
    }

    def __init__(self):
        self.current_lang = 'ru'

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        MainWindow.setWindowIcon(QtGui.QIcon('res/icon.ico'))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gamma_tab = QtWidgets.QTabWidget(self.centralwidget)
        self.gamma_tab.setGeometry(QtCore.QRect(10, 10, 621, 421))
        self.gamma_tab.setObjectName("gamma_tab")
        self.ceaser_tab = QtWidgets.QWidget()
        self.ceaser_tab.setObjectName("ceaser_tab")
        self.label = QtWidgets.QLabel(self.ceaser_tab)
        self.label.setGeometry(QtCore.QRect(30, 20, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.main_text = QtWidgets.QLineEdit(self.ceaser_tab)
        self.main_text.setGeometry(QtCore.QRect(30, 50, 451, 22))
        self.main_text.setObjectName("main_text")
        self.label_2 = QtWidgets.QLabel(self.ceaser_tab)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.results_table = QtWidgets.QTableWidget(self.ceaser_tab)
        self.results_table.setGeometry(QtCore.QRect(30, 120, 561, 251))
        self.results_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.results_table.setColumnCount(0)
        self.results_table.setObjectName("results_table")
        self.results_table.setRowCount(0)
        self.figure_out_button = QtWidgets.QPushButton(self.ceaser_tab)
        self.figure_out_button.setGeometry(QtCore.QRect(500, 45, 93, 28))
        self.figure_out_button.setObjectName("figure_out_button")
        self.current_lang_label = QtWidgets.QLabel(self.ceaser_tab)
        self.current_lang_label.setGeometry(QtCore.QRect(500, 20, 91, 16))
        self.current_lang_label.setObjectName("current_lang_label")
        self.label_3 = QtWidgets.QLabel(self.ceaser_tab)
        self.label_3.setGeometry(QtCore.QRect(380, 20, 111, 16))
        self.label_3.setObjectName("label_3")
        self.gamma_tab.addTab(self.ceaser_tab, "")
        self.tarabarian_tab = QtWidgets.QWidget()
        self.tarabarian_tab.setObjectName("tarabarian_tab")
        self.label_4 = QtWidgets.QLabel(self.tarabarian_tab)
        self.label_4.setGeometry(QtCore.QRect(30, 20, 231, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.main_text_2 = QtWidgets.QLineEdit(self.tarabarian_tab)
        self.main_text_2.setGeometry(QtCore.QRect(30, 50, 451, 22))
        self.main_text_2.setObjectName("main_text_2")
        self.encrypt_tarabarian_button = QtWidgets.QPushButton(self.tarabarian_tab)
        self.encrypt_tarabarian_button.setGeometry(QtCore.QRect(500, 45, 101, 28))
        self.encrypt_tarabarian_button.setObjectName("encrypt_tarabarian_button")
        self.label_5 = QtWidgets.QLabel(self.tarabarian_tab)
        self.label_5.setGeometry(QtCore.QRect(30, 90, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.cipher_text = QtWidgets.QLineEdit(self.tarabarian_tab)
        self.cipher_text.setGeometry(QtCore.QRect(30, 120, 451, 22))
        self.cipher_text.setObjectName("cipher_text")
        self.decrypt_tarabarian_button = QtWidgets.QPushButton(self.tarabarian_tab)
        self.decrypt_tarabarian_button.setGeometry(QtCore.QRect(500, 115, 101, 28))
        self.decrypt_tarabarian_button.setObjectName("decrypt_tarabarian_button")
        self.gamma_tab.addTab(self.tarabarian_tab, "")
        self.vigenere_tab = QtWidgets.QWidget()
        self.vigenere_tab.setObjectName("vigenere_tab")
        self.label_6 = QtWidgets.QLabel(self.vigenere_tab)
        self.label_6.setGeometry(QtCore.QRect(30, 20, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.main_text_3 = QtWidgets.QLineEdit(self.vigenere_tab)
        self.main_text_3.setGeometry(QtCore.QRect(30, 50, 451, 22))
        self.main_text_3.setObjectName("main_text_3")
        self.encrypt_vijn_button = QtWidgets.QPushButton(self.vigenere_tab)
        self.encrypt_vijn_button.setGeometry(QtCore.QRect(500, 45, 101, 28))
        self.encrypt_vijn_button.setObjectName("encrypt_vijn_button")
        self.label_7 = QtWidgets.QLabel(self.vigenere_tab)
        self.label_7.setGeometry(QtCore.QRect(30, 160, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.cipher_text_2 = QtWidgets.QLineEdit(self.vigenere_tab)
        self.cipher_text_2.setGeometry(QtCore.QRect(30, 190, 451, 22))
        self.cipher_text_2.setObjectName("cipher_text_2")
        self.decrypt_vijn_button = QtWidgets.QPushButton(self.vigenere_tab)
        self.decrypt_vijn_button.setGeometry(QtCore.QRect(500, 185, 101, 28))
        self.decrypt_vijn_button.setObjectName("decrypt_vijn_button")
        self.label_8 = QtWidgets.QLabel(self.vigenere_tab)
        self.label_8.setGeometry(QtCore.QRect(30, 90, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.key_text = QtWidgets.QLineEdit(self.vigenere_tab)
        self.key_text.setGeometry(QtCore.QRect(30, 120, 451, 22))
        self.key_text.setObjectName("key_text")
        self.label_9 = QtWidgets.QLabel(self.vigenere_tab)
        self.label_9.setGeometry(QtCore.QRect(380, 20, 111, 16))
        self.label_9.setTextFormat(QtCore.Qt.AutoText)
        self.label_9.setObjectName("label_9")
        self.current_lang_label_2 = QtWidgets.QLabel(self.vigenere_tab)
        self.current_lang_label_2.setGeometry(QtCore.QRect(500, 20, 91, 16))
        self.current_lang_label_2.setObjectName("current_lang_label_2")
        self.gamma_tab.addTab(self.vigenere_tab, "")
        self.tritemius_tab = QtWidgets.QWidget()
        self.tritemius_tab.setObjectName("tritemius_tab")
        self.label_10 = QtWidgets.QLabel(self.tritemius_tab)
        self.label_10.setGeometry(QtCore.QRect(30, 20, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.main_text_4 = QtWidgets.QLineEdit(self.tritemius_tab)
        self.main_text_4.setGeometry(QtCore.QRect(30, 50, 451, 22))
        self.main_text_4.setObjectName("main_text_4")
        self.encrypt_tritemius_button = QtWidgets.QPushButton(self.tritemius_tab)
        self.encrypt_tritemius_button.setGeometry(QtCore.QRect(500, 45, 101, 28))
        self.encrypt_tritemius_button.setObjectName("encrypt_tritemius_button")
        self.label_11 = QtWidgets.QLabel(self.tritemius_tab)
        self.label_11.setGeometry(QtCore.QRect(380, 20, 111, 16))
        self.label_11.setTextFormat(QtCore.Qt.AutoText)
        self.label_11.setObjectName("label_11")
        self.current_lang_label_3 = QtWidgets.QLabel(self.tritemius_tab)
        self.current_lang_label_3.setGeometry(QtCore.QRect(500, 20, 91, 16))
        self.current_lang_label_3.setObjectName("current_lang_label_3")
        self.label_12 = QtWidgets.QLabel(self.tritemius_tab)
        self.label_12.setGeometry(QtCore.QRect(30, 90, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.key_text_2 = QtWidgets.QLineEdit(self.tritemius_tab)
        self.key_text_2.setGeometry(QtCore.QRect(30, 120, 451, 22))
        self.key_text_2.setObjectName("key_text_2")
        self.label_13 = QtWidgets.QLabel(self.tritemius_tab)
        self.label_13.setGeometry(QtCore.QRect(30, 160, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.cipher_text_3 = QtWidgets.QLineEdit(self.tritemius_tab)
        self.cipher_text_3.setGeometry(QtCore.QRect(30, 190, 451, 22))
        self.cipher_text_3.setObjectName("cipher_text_3")
        self.decrypt_tritemius_button = QtWidgets.QPushButton(self.tritemius_tab)
        self.decrypt_tritemius_button.setGeometry(QtCore.QRect(500, 185, 101, 28))
        self.decrypt_tritemius_button.setObjectName("decrypt_tritemius_button")
        self.gamma_tab.addTab(self.tritemius_tab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(30, 20, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(380, 20, 111, 16))
        self.label_15.setTextFormat(QtCore.Qt.AutoText)
        self.label_15.setObjectName("label_15")
        self.current_lang_label_4 = QtWidgets.QLabel(self.tab)
        self.current_lang_label_4.setGeometry(QtCore.QRect(500, 20, 91, 16))
        self.current_lang_label_4.setObjectName("current_lang_label_4")
        self.encrypt_gamma_button = QtWidgets.QPushButton(self.tab)
        self.encrypt_gamma_button.setGeometry(QtCore.QRect(500, 45, 101, 28))
        self.encrypt_gamma_button.setObjectName("encrypt_gamma_button")
        self.main_text_5 = QtWidgets.QLineEdit(self.tab)
        self.main_text_5.setGeometry(QtCore.QRect(30, 50, 451, 22))
        self.main_text_5.setObjectName("main_text_5")
        self.key_text_3 = QtWidgets.QLineEdit(self.tab)
        self.key_text_3.setGeometry(QtCore.QRect(30, 120, 451, 22))
        self.key_text_3.setObjectName("key_text_3")
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(30, 90, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(30, 160, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gamma_result_label = QtWidgets.QLabel(self.tab)
        self.gamma_result_label.setGeometry(QtCore.QRect(30, 190, 571, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei Light")
        font.setPointSize(14)
        self.gamma_result_label.setFont(font)
        self.gamma_result_label.setText("")
        self.gamma_result_label.setObjectName("gamma_result_label")
        self.gamma_tab.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_russian = QtWidgets.QAction(MainWindow)
        self.action_russian.setObjectName("action_russian")
        self.action_russian_short = QtWidgets.QAction(MainWindow)
        self.action_russian_short.setObjectName("action_russian_short")
        self.action_english = QtWidgets.QAction(MainWindow)
        self.action_english.setObjectName("action_english")
        self.menu.addAction(self.action_russian)
        self.menu.addAction(self.action_russian_short)
        self.menu.addAction(self.action_english)
        self.menubar.addAction(self.menu.menuAction())

        self.action_russian.triggered.connect(lambda: self.change_lang('ru'))
        self.action_russian_short.triggered.connect(lambda: self.change_lang('ru_short'))
        self.action_english.triggered.connect(lambda: self.change_lang('en'))
        self.results_table.setColumnCount(2)
        self.results_table.setHorizontalHeaderLabels(('Преобразованный текст', 'Ключ'))
        self.results_table.setColumnWidth(0,450)
        self.results_table.setColumnWidth(1,50)
        self.figure_out_button.clicked.connect(self.ceaser)

        self.encrypt_tarabarian_button.clicked.connect(lambda: self.tarabar(True))
        self.decrypt_tarabarian_button.clicked.connect(lambda: self.tarabar(False))
        self.encrypt_vijn_button.clicked.connect(lambda: self.vijn(True))
        self.decrypt_vijn_button.clicked.connect(lambda: self.vijn(False))
        self.encrypt_tritemius_button.clicked.connect(lambda: self.tritemius(True))
        self.decrypt_tritemius_button.clicked.connect(lambda: self.tritemius(False))
        self.encrypt_gamma_button.clicked.connect(self.gamma)

        self.retranslateUi(MainWindow)
        self.gamma_tab.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SHIFR"))
        self.label.setText(_translate("MainWindow", "Текст"))
        self.label_2.setText(_translate("MainWindow", "Результаты"))
        self.figure_out_button.setText(_translate("MainWindow", "Рассчитать"))
        self.current_lang_label.setText(_translate("MainWindow", "Русский"))
        self.label_3.setText(_translate("MainWindow", "Язык шифра:"))
        self.gamma_tab.setTabText(self.gamma_tab.indexOf(self.ceaser_tab), _translate("MainWindow", "Цезарь"))
        self.label_4.setText(_translate("MainWindow", "Текст (только русский)"))
        self.encrypt_tarabarian_button.setText(_translate("MainWindow", "Зашифровать"))
        self.label_5.setText(_translate("MainWindow", "Шифр"))
        self.decrypt_tarabarian_button.setText(_translate("MainWindow", "Расшифровать"))
        self.gamma_tab.setTabText(self.gamma_tab.indexOf(self.tarabarian_tab), _translate("MainWindow", "Тарабарская"))
        self.label_6.setText(_translate("MainWindow", "Текст"))
        self.encrypt_vijn_button.setText(_translate("MainWindow", "Зашифровать"))
        self.label_7.setText(_translate("MainWindow", "Шифр"))
        self.decrypt_vijn_button.setText(_translate("MainWindow", "Расшифровать"))
        self.label_8.setText(_translate("MainWindow", "Ключ"))
        self.label_9.setText(_translate("MainWindow", "Язык шифра:"))
        self.current_lang_label_2.setText(_translate("MainWindow", "Русский"))
        self.gamma_tab.setTabText(self.gamma_tab.indexOf(self.vigenere_tab), _translate("MainWindow", "Виженер"))
        self.label_10.setText(_translate("MainWindow", "Текст"))
        self.encrypt_tritemius_button.setText(_translate("MainWindow", "Зашифровать"))
        self.label_11.setText(_translate("MainWindow", "Язык шифра:"))
        self.current_lang_label_3.setText(_translate("MainWindow", "Русский"))
        self.label_12.setText(_translate("MainWindow", "Ключ"))
        self.label_13.setText(_translate("MainWindow", "Шифр"))
        self.decrypt_tritemius_button.setText(_translate("MainWindow", "Расшифровать"))
        self.gamma_tab.setTabText(self.gamma_tab.indexOf(self.tritemius_tab), _translate("MainWindow", "Тритемиус"))
        self.label_14.setText(_translate("MainWindow", "Текст"))
        self.label_15.setText(_translate("MainWindow", "Язык шифра:"))
        self.current_lang_label_4.setText(_translate("MainWindow", "Русский"))
        self.encrypt_gamma_button.setText(_translate("MainWindow", "Зашифровать"))
        self.label_16.setText(_translate("MainWindow", "Ключ"))
        self.label_17.setText(_translate("MainWindow", "Шифр"))
        self.gamma_tab.setTabText(self.gamma_tab.indexOf(self.tab), _translate("MainWindow", "Гаммирование"))
        self.menu.setTitle(_translate("MainWindow", "Язык шифра"))
        self.action_russian.setText(_translate("MainWindow", "Русский"))
        self.action_russian_short.setText(_translate("MainWindow", "Русский без \"ё\""))
        self.action_english.setText(_translate("MainWindow", "English"))

    def ceaser(self):
        res = Shifry().ceaser(self.main_text.text(), self.current_lang)
        self.load_table(res)

    def tarabar(self, is_encrypt):
        if is_encrypt:
            res = Shifry().tarabar(self.main_text_2.text(), is_encrypt)
            self.cipher_text.setText(res)
        else:
            res = Shifry().tarabar(self.cipher_text.text(), is_encrypt)
            self.main_text_2.setText(res)

    def vijn(self, is_encrypt):
        if self.key_text.text() != '':
            if is_encrypt:
                if self.main_text_3.text() == '':
                    return
                res = Shifry().encode_vijn(self.main_text_3.text(), self.key_text.text(), self.current_lang)
                self.cipher_text_2.setText(res)
            else:
                if self.cipher_text_2.text() == '':
                    return
                res = Shifry().decode_vijn(self.cipher_text_2.text(), self.key_text.text(), self.current_lang)
                self.main_text_3.setText(res)

    def tritemius(self, is_encrypt):
        if self.key_text_2.text() != '':
            if is_encrypt:
                if self.main_text_4.text() == '':
                    return
                res = Shifry().encode_tritemius(self.main_text_4.text(), self.key_text_2.text(), self.current_lang)
                self.cipher_text_3.setText(res)
            else:
                if self.cipher_text_3.text() == '':
                    return
                res = Shifry().decode_tritemius(self.cipher_text_3.text(), self.key_text_2.text(), self.current_lang)
                self.main_text_4.setText(res)

    def gamma(self):
        self.gamma_result_label.setText(Shifry().encode_gamma(self.main_text_5.text(), self.key_text_3.text(), self.current_lang))

    def load_table(self, data):
        self.results_table.setRowCount(len(data.keys()))
        for i in range(len(data.keys())):
            key = str(i)
            self.results_table.setItem(i, 1, QtWidgets.QTableWidgetItem(key))
            self.results_table.setItem(i, 0, QtWidgets.QTableWidgetItem(str(data[i])))

    def change_lang(self, lang):
        self.current_lang = lang
        self.current_lang_label.setText(self.langs[lang])
        self.current_lang_label_2.setText(self.langs[lang])
        self.current_lang_label_3.setText(self.langs[lang])
        self.current_lang_label_4.setText(self.langs[lang])
